apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lms-app.fullname" . }}-admin-secret
  labels:
    {{- include "lms-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.frappe.adminPassword | b64enc | quote }}

